version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: marketing-agency-portal
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "5002:5002"
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - mongodb

volumes:
  mongodb_data:
